version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production

  user-service:
    build: ./services/user-service
    ports:
      - "5002:5002"

  hotel-service:
    build: ./services/hotel-service
    ports:
      - "5003:5003"

  booking-service:
    build: ./services/booking-service
    ports:
      - "5004:5004"

  payment-service:
    build: ./services/payment-service
    ports:
      - "5005:5005"

  notification-service:
    build: ./services/notification-service
    ports:
      - "5006:5006"

  api-gateway:
    build: ./gateway
    ports:
      - "3000:3000"
